export const PrivacyPolicy = () => {
  return (
    <div className="policy-content">
      <div className="policy-head u-h3">PRIVACY POLICY</div>
      <h4 className="policy-subhead u-h4">What is Ophelia moon?</h4>
      <div className="policy-subhead u-h5">
        Ophelia moon: This Website and its Legal Policies
      </div>
      <div className="policy-text  u-h4">
        ( Please read these Terms of Use carefully before using our Platforms. )
      </div>
      <p className="policy-text  u-h4">
        This Privacy Policy describes our policies and procedures on the
        collection, use and disclosure of your information when you use the
        Service and tells you about your privacy rights and how the law protects
        you. We use your personal data to provide and improve the Service. By
        using the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h4 className="policy-subhead u-h4">Interpretation and Definitions</h4>
      <div className="policy-subhead u-h4">Interpretation</div>
      <p className="policy-text  u-h4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <div className="policy-subhead u-h4">Definition</div>
      <div className="policy-subhead u-h5">
        For the purposes of this Privacy Policy <span className="u-h3">:</span>
      </div>
      <p className="policy-text  u-h4">
        The brand Ophelia moon Jewellery (also known as “OM”) is held by the company
        name……….address…….
      </p>

      <ul>
        <li>
          Cookies are small files that are placed on your computer, mobile phone
          or any other device by a website, containing the details of your
          browsing history on that website among its many uses means.
        </li>
        <li>
          Device means any device that can access the Service such as a laptop,
          computer, a mobile phone or a digital tablet.
        </li>
        <li>
          Personal Data is any information that relates to an identified or
          recollected individual.
        </li>
        <li>
          Service provider means any natural or legal person who processes the
          data on behalf of the Company. It refers to the third-party companies
          or individuals employed by the Company to facilitate the Service, to
          provide the Service on behalf of the Company, to perform services
          related to the Service or to assist the Company in analysing how the
          Service is used.
        </li>
        <li>
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).
        </li>
        <li>
          Website refers to Ophelia moon, accessible from the website
          <a href="www.meme-india.com/">(www.meme-india.com/)</a>.
        </li>
        <li>
          You means the individual accessing or using the Website, Service, or
          the Company, or other legal entity on behalf of which such individual
          is accessing or using the Service, as applicable.
        </li>
      </ul>
      <div className="policy-subhead u-h4">
        Collecting and Using Your Personal Data
      </div>
      <div className="policy-subhead u-h5">Types of Data Collected</div>
      <div className="policy-subhead u-h5">Personal Data</div>
      <p className="policy-text  u-h4">
        While using Our Service, We may ask You certain personally identifiable
        information that can be used to contact or identify You. To access our
        website, you will need to register with our services. During the
        registration process, you will be asked to provide personal information
        about yourself (which includes your name, address, date of birth, email
        and phone number). By entering your details in the required fields, you
        allow Ophelia moon to provide you with the services you select.
      </p>

      <ul>
        <li>
          When you purchase products online or over the phone, we collect
          information such as your purchase details and relevant payment
          information. In addition, we will also collect personal information
          about you when you communicate with us (for example, if you contact us
          with a doubt and query about one of our products or services), when
          you provide your contact details while visiting our website. Please
          note that the call will occasionally be recorded for security,
          training, and improvement purposes.
        </li>
        <li>
          If you choose to interact with Ophelia moon through a social media platform
          or other third party services we will collect the information you have
          provided to us through that platform.
        </li>
        <li>
          Personal Data is any information that relates to an identified or
          recollected individual.
        </li>
        <li>
          Service provider means any natural or legal person who processes the
          data on behalf of the Company. It refers to the third-party companies
          or individuals employed by the Company to facilitate the Service, to
          provide the Service on behalf of the Company, to perform services
          related to the Service or to assist the Company in analysing how the
          Service is used.
        </li>
        <li>
          We also automatically collect certain information about the one that
          makes formal visits of inspection to our Platform (Visitors), detailed
          in the section entitled “Cookies and other information we collect
          automatically”.
        </li>
        <li>
          We will collect certain information relating to our visitors location,
          as we provide any location services, as described in the “Location
          Services” section below.
        </li>
      </ul>
      <div className="policy-subhead u-h5">
        We will use the information collect from you to
        <span className="u-h3">:</span>
      </div>
      <ul>
        <li>Manage our accounts and records;</li>
        <li>Manage and respond to repair requests;</li>
        <li>Deal with your enquiries and requests;</li>
        <li>
          Send service related communications, including announcements and
          administrative messages such as order confirmation.
        </li>
        <li>
          Recognize products and services that we think may be of interest to
          you, based on your information such as your purchase history and your
          previous interactions with us;
        </li>
        <li>
          Send you marketing communications (including emails and social media
          audience correspondence) relating to us and other third party partners
          which we believe may be of interest to you, where we have a legitimate
          basis for doing so (please see the “Your Choices ” section below for
          more information on how you can control these communications);
        </li>
        <li>
          Conduct market research so that we do the improvement of the services
          we provide to our clients.
        </li>
        <li>
          Perform credit checks, prevent fraud and other prohibited or illegal
          activities, as part of our efforts to keep our Platform and services
          secure; as well as part of our efforts to maintain the security of our
          Platform; and understand the use of our Platform so that we can
          continuously improve our Platform and services and other offerings.
        </li>
      </ul>
      <div className="policy-subhead u-h5">Usage Data</div>
      <p className="policy-text  u-h4">
        Usage Data is collected automatically when using the Website Service.
      </p>
      <p className="policy-text  u-h4">
        Usage Data may include information such as Your Mobile Phone's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="policy-text  u-h4">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="policy-text  u-h4">
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        phone device.
      </p>
      <div className="policy-subhead u-h5">
        Tracking Technologies and Cookies
      </div>
      <p className="policy-text  u-h4">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyse Our Service. The technologies We use may contain:
      </p>
      <p className="policy-text  u-h4">
        Usage Data may include information such as Your Mobile Phone's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="policy-text  u-h4">
        <strong>Cookies or Browser Cookies: </strong> A cookie is a small file
        placed on Your Device when you use. You can instruct Your browser to
        refuse all Cookies or to indicate when a Cookie is being sent. However,
        if You do not accept Cookies, You may not be able to use some parts of
        our Website Service. Unless you have adjusted Your browser setting so
        that it will refuse Cookies, our Service may use Cookies.
      </p>
      <p className="policy-text  u-h4">
        <strong>Flash Cookies: </strong> Certain features of our Website Service
        may use local stored objects (or Flash Cookies) to collect and store
        information about Your preferences or Your activity on our Service.
        Flash Cookies are not managed by the same browser settings as those used
        for Browser Cookies.
      </p>
      <p className="policy-text  u-h4">
        <strong>Web Beacons: </strong> : Certain sections of our Service and our
        emails may contain small electronic files known as web beacons (also
        referred to as clear gifs, pixel tags, and single-pixel gifs) that
        permit the Company, for example, to count users who have visited those
        pages or opened an email and for other related website statistics (for
        example, recording the popularity of a certain section and verifying
        system and server integrity).
      </p>
      <p className="policy-text  u-h4">
        Cookies can be “Persistent”; or “Session”; Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web browser.
        You can learn more about cookies here:{" "}
      </p>
      <div className="policy-subhead u-h5">
        We use both Session and Persistent Cookies for the purposes set out
        below
        <span className="u-h3">:</span>
      </div>

      <ul>
        <li>Necessary / Essential Cookies</li>
        <p className="policy-text  u-h4">Type: Session Cookies</p>
        <p className="policy-text  u-h4">Administered by: Us</p>
        <p className="policy-text  u-h4">
          Purpose: These Cookies are essential to provide You with services
          available through the Website and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use
          of user accounts. Without these Cookies, the services that You have
          asked for can’t be provided, and We only use these Cookies to provide
          You secure services.
        </p>
        <li>Necessary / Essential Cookies</li>
        <p className="policy-text  u-h4">Type: Session Cookies</p>
        <p className="policy-text  u-h4">Administered by: Us</p>
        <p className="policy-text  u-h4">
          Purpose: These Cookies are essential to provide You with services
          available through the Website and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use
          of user accounts. Without these Cookies, the services that You have
          asked for can’t be provided, and We only use these Cookies to provide
          You secure services.
        </p>
        <li>Cookies Policy / Notice Acceptance Cookies</li>
        <p className="policy-text  u-h4">Type: Persistent Cookies</p>
        <p className="policy-text  u-h4">Administered by: US</p>
        <p className="policy-text  u-h4">
          Purpose: These Cookies identify if users have accepted the use of
          cookies on the Website.
        </p>
        <li>Functionality Cookies</li>
        <p className="policy-text  u-h4">Type: Persistent Cookies</p>
        <p className="policy-text  u-h4">Administered by: US</p>
        <p className="policy-text  u-h4">
          Purpose: These Cookies allow us to remember choices You make when You
          use the Website, such as remembering your login details or language
          preference. The purpose of these Cookies is to provide You with a more
          personal experience and to avoid You having to re-enter your
          preferences every time You use the Website.
        </p>
        <p className="policy-text  u-h4">
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the Cookies
          section of our Privacy Policy.
        </p>
      </ul>
      <div className="policy-subhead u-h4">Use of Your Personal Data</div>
      <div className="policy-subhead u-h5">
        The Company may use Personal Data for the following purposes:
      </div>

      <ul>
        <li>
          <strong>To provide and maintain our Service,</strong>including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong>to manage Your registration as
          a user of the Service. The Personal Data You provide can give You
          access to different functionalities of the Service that are available
          to You as a registered user.
        </li>
        <li>
          <strong>For the performance of a contract: </strong> the development,
          compliance and undertaking of the purchase contract for the products,
          items or services You have purchased or of any other contract with Us
          through the Service.
        </li>
        <li>
          <strong>To contact You:</strong>To contact You by email, phone calls,
          SMS, or other equivalent forms of electronic communication, such as a
          mobile application's push notifications regarding updates or
          informative communications related to the functionalities, products or
          contracted services, including the security updates, when necessary or
          reasonable for their implementation.
        </li>
        <li>
          <strong>To provide You</strong> with current news, special offers and
          general information about other goods, services and events which we
          offer that are similar to those that you have already purchased or
          enquired about unless You have opted not to receive such information.
        </li>
        <li>
          <strong>To manage Your requests: </strong>To attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers: </strong>We may use Your information
          to evaluate or conduct a merger, divestiture, restructuring,
          reorganization, dissolution, or other sale or transfer of some or all
          of Our assets, whether as a going concern or as part of bankruptcy,
          liquidation, or similar proceeding, in which Personal Data held by Us
          about our Service users is among the assets transferred.
        </li>
        <li>
          <strong>For other purposes:</strong>We may use Your information for
          other purposes, such as data analysis, identifying usage trends,
          determining the effectiveness of our promotional campaigns and to
          evaluate and improve our Website Service, products, services,
          marketing and your experience.
        </li>
      </ul>
      <div className="policy-subhead u-h5">
        We may share Your personal information in the following situations:-
      </div>

      <ul>
        <li>
          <strong>With Service Providers:</strong>We may share Your personal
          information with Service Providers to monitor and analyse the use of
          our Service, to contact You.
        </li>
        <li>
          <strong>For business transfers: </strong>We may share or transfer Your
          personal information in connection with, or during negotiations of,
          any merger, sale of Company assets, financing, or acquisition of all
          or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your information with
          Our affiliates, in which case we will require those affiliates to
          honour this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries, joint venture partners or other companies that
          We control or that are under common control with Us.
        </li>
        <li>
          <strong>With business partners:</strong>when You share personal
          information or otherwise interact in the public areas with other
          users, such information may be viewed by all users and may be publicly
          distributed outside.
        </li>
        <li>
          <strong>With other users: </strong> with current news, special offers
          and general information about other goods, services and events which
          we offer that are similar to those that you have already purchased or
          enquired about unless You have opted not to receive such information.
        </li>
        <li>
          <strong>With Your consent: </strong> We may disclose Your personal
          information for any other purpose with Your consent.
        </li>
      </ul>
      <div className="policy-subhead u-h5">Retention of Your Personal Data</div>
      <p className="policy-text  u-h4">
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </p>
      <p className="policy-text  u-h4">
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </p>
      <div className="policy-subhead u-h5">Transfer of Your Personal Data</div>
      <p className="policy-text  u-h4">
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ than those from Your jurisdiction.
      </p>
      <p className="policy-text  u-h4">
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>
      <p className="policy-text  u-h4">
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </p>
      <div className="policy-subhead u-h4">
        Disclosure of Your Personal Data
      </div>
      <div className="policy-subhead u-h5">Business Transactions</div>
      <p className="policy-text  u-h4">
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </p>

      <div className="policy-subhead u-h5">Law enforcement</div>
      <p className="policy-text  u-h4">
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <div className="policy-subhead u-h5">Other legal requirements</div>
      <p className="policy-text  u-h4">
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>
      <div className="policy-subhead u-h5">Security of Your Personal Data</div>
      <p className="policy-text  u-h4">
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
      <div className="policy-subhead u-h5">Children's Privacy</div>
      <p className="policy-text  u-h4">
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>
      <p className="policy-text  u-h4">
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent's consent before We collect and use that
        information.
      </p>
      <div className="policy-subhead u-h5">Links to Other Websites:- </div>
      <p className="policy-text  u-h4">
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p className="policy-text  u-h4">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <div className="policy-subhead u-h5">Changes to this Privacy Policy </div>
      <p className="policy-text  u-h4">
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="policy-text  u-h4">
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the “Last updated”;
        date at the top of this Privacy Policy.
      </p>
      <p className="policy-text  u-h4">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <div className="policy-subhead u-h5">Contact Us :-</div>
      <p className="policy-text  u-h4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <p className="policy-text  u-h4">
        By visiting this page on our website:-
      </p>
      <p className="policy-text  u-h4">
        <a href="https://www.instagram.com/Ophelia-moonfashions/">
          https://www.instagram.com/Ophelia-moonfashions/
        </a>
      </p>
    </div>
  );
};
